// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Url struct {
	ID        int64
	LongUrl   string
	ShortUrl  string
	CreatedAt pgtype.Timestamp
	ExpiredAt pgtype.Timestamp
}
