// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: url.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const shortenUrl = `-- name: ShortenUrl :one
INSERT INTO urls (
    long_url,
    short_url,
    expired_at
) VALUES (
    $1, $2, $3
) returning id, long_url, short_url, created_at, expired_at
`

type ShortenUrlParams struct {
	LongUrl   string
	ShortUrl  string
	ExpiredAt pgtype.Timestamp
}

func (q *Queries) ShortenUrl(ctx context.Context, db DBTX, arg ShortenUrlParams) (Url, error) {
	row := db.QueryRow(ctx, shortenUrl, arg.LongUrl, arg.ShortUrl, arg.ExpiredAt)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.LongUrl,
		&i.ShortUrl,
		&i.CreatedAt,
		&i.ExpiredAt,
	)
	return i, err
}
